const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
const HANDLE_AUTHENTICATE_RESULT = 'HANDLE_AUTHENTICATE_RESULT'
const HANDLE_REGISTRATION_RESULT = 'HANDLE_REGISTRATION_RESULT'
const PUT_RESOURCES = 'PUT_RESOURCES'
const PUT_CART_INFORMATION = 'PUT_CART_INFORMATION'
const PUT_CART_PRODUCTS = 'PUT_CART_PRODUCTS'

export {
    SET_AUTHENTICATED,
    HANDLE_AUTHENTICATE_RESULT,
    HANDLE_REGISTRATION_RESULT,
    PUT_RESOURCES,
    PUT_CART_INFORMATION,
    PUT_CART_PRODUCTS
}